spring:
  config:
    activate:
      on-profile: "h2"
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:coffdb;NON_KEYWORDS=USER;MODE=MySQL
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
#  sql:
#    init:
#      data-locations: classpath:database/data.sql
#      mode: always
#      platform: h2
