springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: method
    path: /swagger-ui
    doc-expansion: none
    urls-primary-name: COFF API DOCS
  api-docs:
    path: /api-docs
  paths-to-match:
    - /v1/**
